### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by yumengzhong** [ParryQiu/IMOOC-React#1]
你好，我在练习react的时候遇到问题，希望得到帮助
![image](https://cloud.githubusercontent.com/assets/16720172/25692208/74a8709e-30d3-11e7-9db5-890ec53957ec.png)

![image](https://cloud.githubusercontent.com/assets/16720172/25692222/8f984730-30d3-11e7-864c-292f628c825f.png)

![image](https://cloud.githubusercontent.com/assets/16720172/25692157/12cb5756-30d3-11e7-93a8-1e1407b05072.png)
![image](https://cloud.githubusercontent.com/assets/16720172/25692162/219252f8-30d3-11e7-98a2-4396b20125cd.png)

编译成功了，但是游览器报错
![image](https://cloud.githubusercontent.com/assets/16720172/25692125/dc88d6fa-30d2-11e7-99d1-008c973256c3.png)

![image](https://cloud.githubusercontent.com/assets/16720172/25692181/34452326-30d3-11e7-9984-577f28b3c2bf.png)

**Comment by ParryQiu** [comment]
这个问题是没有加载到 CSS 对应的 loader 造成的，你尝试删除 node_modules 文件夹后重新执行 npm install 加载所有的包再编译运行试一下。

**Comment by yumengzhong** [comment]
@ParryQiu 后来我通过另一种方式实现了，您说的我还没有实验
![image](https://cloud.githubusercontent.com/assets/16720172/25733972/00c0340a-3191-11e7-961e-7811d329d956.png)

**Comment by ParryQiu** [comment]
绿框不行是因为没有加载 babel-plugin-react-html-attrs 包。
不过我看你已经配置了，应该还是包加载的问题。
你可以删除了重新加载包试试。

**Comment by zengyanzi** [comment]
我也出现类似的问题，而且不仅是css，css搞定了之后还有如下问题，是loader需要重新配置了吗？多谢
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'style-loader' instead of 'style',
                 see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed
 @ ./src/js/components/footer.js 17:14-45
 @ ./src/js/index.js

**Comment by ParryQiu** [comment]
@zengyanzi  配置文件中的 style 修改成 style-loader 即可。你应该是安装了 2.0 的 webpack，配置需要进行相应的变更。

**Comment by zengyanzi** [comment]
@ParryQiu 非常感谢！！！
